# 非 host 版本, 不使用本机代理
version: '3.3'
services:
  pg:
    # image: ankane/pgvector:v0.4.2 # dockerhub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/pgvector:v0.4.2 # 阿里云
    container_name: pg
    restart: always
    ports: # 生产环境建议不要暴露
      - 8100:5432
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - POSTGRES_USER=fastgpt
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastgpt
    volumes:
      # 刚创建的文件
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sh
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    # image: mongo:5.0.18
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18 # 阿里云
    container_name: mongo
    restart: always
    ports: # 生产环境建议不要暴露
      - 27017:27017
    networks:
      - fastgpt
    environment:
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      -  /home/fastgpt/FastGPT/docs/deploy/fastgpt/mongo/data:/data/db
      -  /home/fastgpt/FastGPT/docs/deploy/fastgpt/mongo/logs:/var/log/mongodb
  fastgpt:
    container_name: fastgpt
    # image: c121914yu/fast-gpt:latest # docker hub
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:latest # 阿里云
    # network_mode: host #
    ports:
      - 3000:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment: # 可选的变量，不需要的话需要去掉
      - PORT=3000 # 运行的端口地址，如果不是 3000，需要修改成实际地址。
      - DB_MAX_LINK=5 # database max link
      # proxy（可选）
      #- AXIOS_PROXY_HOST=127.0.0.1
      #- AXIOS_PROXY_PORT=7890
      # 发送邮箱验证码配置。用的是QQ邮箱。参考 nodeMail 获取MAILE_CODE，自行百度。
      - MY_MAIL=onexixi@foxmail.com
      - MAILE_CODE=alxicsxbtsirdcbh
      # token加密凭证（随便填，作为登录凭证）
      - TOKEN_KEY=any
      # root key, 最高权限，可以内部接口互相调用
      - ROOT_KEY=root_key
      # 和上方mongo镜像的username,password对应
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      - PG_HOST=pg
      - PG_PORT=5432
      # 和上方PG镜像对应.
      - PG_USER=fastgpt
      - PG_PASSWORD=1234
      - PG_DB_NAME=fastgpt
      # openai 相关配置：使用了 oneapi 后，下面只需要填下 OPENAI_BASE_URL （国外可全忽略）
      - OPENAIKEY=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
      - OPENAI_BASE_URL=https://vojntypggbpu.cloud.sealos.io/openai/v1
      - OPENAI_BASE_URL_AUTH=auth
  fastgpt-admin:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt-admin:latest
    container_name: fastgpt-admin
    restart: always
    ports:
      - 3001:3001
    networks:
      - fastgpt
    depends_on:
      - mongo
      - fastgpt
    environment:
      - MONGODB_URI=mongodb://username:password@mongo:27017/?authSource=admin
      - MONGODB_NAME=fastgpt
      - ADMIN_USER=username
      - ADMIN_PASS=password
      - ADMIN_SECRET=any
      - PARENT_URL=http://fastgpt:3000
      - PARENT_ROOT_KEY=root_key
  keyadmin:
    container_name: keyadmin
    image: justsong/one-api
    restart: always
    ports:
      - 3002:3000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /keyadmin:/data
  nginx: # 宝塔不需要额外装 nginx
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/nginx:alpine3.17
    # image: nginx:alpine3.17
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      # 刚创建的文件
      - /home/fastgpt/FastGPT/docs/deploy/fastgpt/nginx
      - /home/fastgpt/FastGPT/docs/deploy/fastgpt/nginx/logs:/var/log/nginx
networks:
  fastgpt:
